---
- name: Install glusterfs
  yum:
    name:
      - centos-release-gluster
- name: Install glusterfs server
  yum:
    name:
      - glusterfs-server
- name: Install xfsprogs
  yum:
    name:
      - xfsprogs
- name: Ensure the GlusterFS service is running (CentOS)
  service: name=glusterd state=started