---
- hosts: webservers
  become: true
  vars_files:
    - ../vars/variables.yml
  pre_tasks:
    - name: Create a directory if it does not exist
      file:
        path: "{{sharedFolder}}/data"
        state: directory
        mode: '0755'
  tasks:  
    - name: Stop docker back container
      shell: docker stop back || true
    - name: remove docker back continer
      shell: docker rm back || true
    - name: remove docker back continer old
      shell: docker rmi zeronetdev/sd-exam-1-back || true
    - name: Start docker back continer
      shell: docker run --name back -d -p 3000:3000 -v {{sharedFolder}}:{{sharedFolder}} --restart unless-stopped -e STORAGE={{sharedFolder}}/data zeronetdev/sd-exam-1-back