---
- hosts: webservers
  become: true
  vars_files:
    - ../vars/variables.yml
  pre_tasks:
    - import_tasks: tasks/docker.yml
  tasks:  
    - name: Stop docker back container
      shell: docker stop back || true
    - name: Start docker back continer
      shell: docker run --name back -d -p 3000:3000 -v {{sharedFolder}}:{{sharedFolder}} --restart unless-stopped zeronetdev/sd-exam-1-back