---
- hosts: all
  become: true
  vars_files:
    - ../vars/variables.yml
  pre_tasks:
    - name: Create a directory if it does not exist
      file:
        path: "{{ sharedFolder }}"
        state: directory
        mode: '0755'
  tasks:
  - name: Ensure Gluster volume is mounted.
    mount:
      name: "{{ volumeName }}"
      src: "localhost:/{{ volumeName }}"
      fstype: glusterfs
      opts: "defaults,_netdev"
      state: mounted